
import Script from 'next/script'
import Footer from './components/footer'
import Navigation from './components/naviagtion'
import './globals.css'
import './css/style.css'
import './css/animate.css'
import './css/aos.css'
import './css/bootstrap-datepicker.css'
import './css/flaticon.css'
import './css/icomoon.css'
import './css/ionicons.min.css'
import './css/jquery.timepicker.css'
import './css/magnific-popup.css'
import './css/open-iconic-bootstrap.min.css'
import './css/owl.carousel.min.css'
import './css/owl.theme.default.min.css'

export const metadata = {
  title: 'Dance with RayRuff',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
            <link href="https://fonts.googleapis.com/css?family=Muli:300,400,600,700" rel="stylesheet" />
            <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet" />
      </head>
      <body>
        {/* < Navigation /> */}
        {children}
        < Footer />

        {/* scripts */}
        <Script src={"js/jquery.min.js"}  strategy='beforeInteractive'/>
        <Script src={"js/jquery-migrate-3.0.1.min.js"}  strategy='beforeInteractive'/>
        <Script src={"js/popper.min.js"} strategy='beforeInteractive' />
        <Script src={"js/bootstrap.min.js"} strategy='beforeInteractive' />
        <Script src={"js/jquery.easing.1.3.js"} strategy='beforeInteractive' />
        <Script src={"js/jquery.waypoints.min.js"} strategy='beforeInteractive' />
        <Script src={"js/jquery.stellar.min.js"} strategy='beforeInteractive' />
        <Script src={"js/owl.carousel.min.js"} strategy='beforeInteractive' />
        <Script src={"js/jquery.magnific-popup.min.js"} strategy='beforeInteractive' />
        <Script src={"js/aos.js"} strategy='beforeInteractive' />
        <Script src={"js/jquery.animateNumber.min.js"} strategy='beforeInteractive' />
        <Script src={"js/bootstrap-datepicker.js"} strategy='beforeInteractive' />
        <Script src={"js/jquery.timepicker.min.js"} strategy='beforeInteractive' />
        <Script src={"js/google-map.js"} strategy='beforeInteractive' />
        <Script src={"js/main.js"} strategy='beforeInteractive' />
        <Script src={"https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&amp;sensor=false"} strategy='beforeInteractive' />
        <Script async src={"https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"} strategy='beforeInteractive' />
      </body>
    </html>
  )
}
